
version: 2
jobs:
  build_test_docs_wheel:
    machine: True
    steps:
      - checkout
      - run: docker pull deltachat/doxygen 
      - run: docker pull deltachat/coredeps
      - run:
          command: |
            echo 'export MESONARGS=""' >> $BASH_ENV 
            echo 'export DOCS=1' >> $BASH_ENV 
            echo 'export TESTS=1' >> $BASH_ENV 
      - run: ci_scripts/ci_run.sh
      - persist_to_workspace: 
          root: ./
          paths: 
            - python/wheelhouse
            - docs/xml
            - docs/html

  upload_docs_wheels:
    machine: True
    steps:
      - run:
          command: |
            echo 'export MESONARGS=""' >> $BASH_ENV 
      - checkout
      - attach_workspace:
          at: workspace
      - run: ci_scripts/ci_upload.sh workspace

  build_monolith_tests:
    machine: True
    steps:
      - checkout
      - run: docker pull deltachat/test7
      - run:
          command: |
            echo 'export MESONARGS="-Dmonolith=true"' >> $BASH_ENV
            echo 'export TESTS=1' >> $BASH_ENV 
      - run: ci_scripts/ci_run.sh

  build_static:
    machine: True
    steps:
      - checkout
      - run: docker pull deltachat/test7
      - run:
          command: |
            echo 'export MESONARGS="--default-library=static"' >> $BASH_ENV
      - run: ci_scripts/ci_run.sh

  build_forcefallback: 
    machine: True
    steps:
      - checkout
      - run: docker pull deltachat/test7
      - run:
          command: |
            echo 'export MESONARGS="--wrap-mode=forcefallback --default-library=static"' >> $BASH_ENV
      - run: ci_scripts/ci_run.sh

workflows:
  version: 2
  build_all:
    jobs:
      - build_test_docs_wheel
      - build_monolith_tests
      - build_static
      - build_forcefallback
      - upload_docs_wheels:
          requires:
              - build_test_docs_wheel
              - build_monolith_tests
              - build_static
              - build_forcefallback
        

