
version: 2
jobs:
  build:
    machine: True
    steps:
      - checkout
      - run: docker pull deltachat/doxygen 
      - run: docker pull deltachat/test7
      - run:
          command: |
            echo 'export DOCS=1' >> $BASH_ENV 
            echo 'export TESTS=1' >> $BASH_ENV 
            echo 'export WHEELS=1' >> $BASH_ENV
      - run: scripts/travisbuild.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
