
version: 2
jobs:
  build:
    machine: True
    steps:
      - checkout
      - run: docker pull deltachat/doxygen 
      - run: docker pull deltachat/test7
      - run: scripts/travisbuild.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build


