
version: 2
jobs:
  build:
    docker:
      - image: deltachat/doxygen 
    steps:
      - checkout
      - run: scripts/doxygen.sh
  #test:
  #  docker:
  #    - image: circleci/<language>:<version TAG>
  #  steps:
  #    - checkout
  #    - run: <command>

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      #- test


